# Generated by Django 5.1.2 on 2024-10-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default='RL Dandelion leaf tea 0765H', max_length=255, null=True)),
                ('supplier', models.CharField(blank=True, default='RUTLAND BIODYNAMICS (Brand)', max_length=255, null=True)),
                ('currency_code', models.CharField(blank=True, default='SGD', max_length=3, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, default=0.13, max_digits=10, null=True)),
                ('uom', models.CharField(blank=True, default='g', max_length=10, null=True)),
                ('discountable_all', models.BooleanField(blank=True, default=False, null=True)),
                ('discountable_members', models.BooleanField(blank=True, default=True, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
