# Generated by Django 5.1.2 on 2024-11-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload a profile photo for the patient.', null=True, upload_to='profile_photos/'),
        ),
    ]
